ServicoController e correções
nicolasgandrade/ac2 pull request #5
Opened 2022-11-10 02:23 UTC by FelipeSFranqueira

Criação do ServicoController, correção leve no banco(algumas palavras estavam com acento), correção na classe Servico, acho que é so isso.

2022-11-10 14:14 UTC, nicolasgandrade requested changes

2022-11-10 14:14 UTC, nicolasgandrade commented on src/utils/ServicoController.java
> +                + "descricao_servico = '" + servico.getDescricao()+ "';";
faltou o where pelo Id

2022-11-14 01:58 UTC, nicolasgandrade commented on src/utils/ServicoController.java
> +                + "descricao_servico = '" + servico.getDescricao()+ "';";
@FelipeSFranqueira Alguma atualização sobre esse PR?

2022-11-14 02:02 UTC, FelipeSFranqueira commented on src/utils/ServicoController.java
> +                + "descricao_servico = '" + servico.getDescricao()+ "';";
Vou mexer nele daqui a pouco

2022-11-14 19:35 UTC, closed without merging